//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesWebServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class LoginRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class LoginResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sid {
            get {
                return this.sidField;
            }
            set {
                if ((this.sidField.Equals(value) != true)) {
                    this.sidField = value;
                    this.RaisePropertyChanged("sid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class LogoutRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sid {
            get {
                return this.sidField;
            }
            set {
                if ((this.sidField.Equals(value) != true)) {
                    this.sidField = value;
                    this.RaisePropertyChanged("sid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class LogoutResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgentInfoRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class GetAgentInfoRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int agentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int agentid {
            get {
                return this.agentidField;
            }
            set {
                if ((this.agentidField.Equals(value) != true)) {
                    this.agentidField = value;
                    this.RaisePropertyChanged("agentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sid {
            get {
                return this.sidField;
            }
            set {
                if ((this.sidField.Equals(value) != true)) {
                    this.sidField = value;
                    this.RaisePropertyChanged("sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgentInfoResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class GetAgentInfoResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.AgentInfoDataContract agentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] callsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.AgentInfoDataContract agentInfo {
            get {
                return this.agentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.agentInfoField, value) != true)) {
                    this.agentInfoField = value;
                    this.RaisePropertyChanged("agentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] calls {
            get {
                return this.callsField;
            }
            set {
                if ((object.ReferenceEquals(this.callsField, value) != true)) {
                    this.callsField = value;
                    this.RaisePropertyChanged("calls");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentInfoDataContract", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class AgentInfoDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int agentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] callsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int agentId {
            get {
                return this.agentIdField;
            }
            set {
                if ((this.agentIdField.Equals(value) != true)) {
                    this.agentIdField = value;
                    this.RaisePropertyChanged("agentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] calls {
            get {
                return this.callsField;
            }
            set {
                if ((object.ReferenceEquals(this.callsField, value) != true)) {
                    this.callsField = value;
                    this.RaisePropertyChanged("calls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallInfoDataContract", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class CallInfoDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calldateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string campaignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customeridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dnisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endreasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string memoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statuscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusdetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusgroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statustextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ani {
            get {
                return this.aniField;
            }
            set {
                if ((object.ReferenceEquals(this.aniField, value) != true)) {
                    this.aniField = value;
                    this.RaisePropertyChanged("ani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calldate {
            get {
                return this.calldateField;
            }
            set {
                if ((object.ReferenceEquals(this.calldateField, value) != true)) {
                    this.calldateField = value;
                    this.RaisePropertyChanged("calldate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callid {
            get {
                return this.callidField;
            }
            set {
                if ((object.ReferenceEquals(this.callidField, value) != true)) {
                    this.callidField = value;
                    this.RaisePropertyChanged("callid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string campaign {
            get {
                return this.campaignField;
            }
            set {
                if ((object.ReferenceEquals(this.campaignField, value) != true)) {
                    this.campaignField = value;
                    this.RaisePropertyChanged("campaign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                if ((object.ReferenceEquals(this.commentsField, value) != true)) {
                    this.commentsField = value;
                    this.RaisePropertyChanged("comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerid {
            get {
                return this.customeridField;
            }
            set {
                if ((object.ReferenceEquals(this.customeridField, value) != true)) {
                    this.customeridField = value;
                    this.RaisePropertyChanged("customerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dnis {
            get {
                return this.dnisField;
            }
            set {
                if ((object.ReferenceEquals(this.dnisField, value) != true)) {
                    this.dnisField = value;
                    this.RaisePropertyChanged("dnis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                if ((object.ReferenceEquals(this.durationField, value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endreason {
            get {
                return this.endreasonField;
            }
            set {
                if ((object.ReferenceEquals(this.endreasonField, value) != true)) {
                    this.endreasonField = value;
                    this.RaisePropertyChanged("endreason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                if ((object.ReferenceEquals(this.memoField, value) != true)) {
                    this.memoField = value;
                    this.RaisePropertyChanged("memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queue {
            get {
                return this.queueField;
            }
            set {
                if ((object.ReferenceEquals(this.queueField, value) != true)) {
                    this.queueField = value;
                    this.RaisePropertyChanged("queue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.statuscodeField, value) != true)) {
                    this.statuscodeField = value;
                    this.RaisePropertyChanged("statuscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusdetail {
            get {
                return this.statusdetailField;
            }
            set {
                if ((object.ReferenceEquals(this.statusdetailField, value) != true)) {
                    this.statusdetailField = value;
                    this.RaisePropertyChanged("statusdetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusgroup {
            get {
                return this.statusgroupField;
            }
            set {
                if ((object.ReferenceEquals(this.statusgroupField, value) != true)) {
                    this.statusgroupField = value;
                    this.RaisePropertyChanged("statusgroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statustext {
            get {
                return this.statustextField;
            }
            set {
                if ((object.ReferenceEquals(this.statustextField, value) != true)) {
                    this.statustextField = value;
                    this.RaisePropertyChanged("statustext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListAgentsRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class ListAgentsRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sid {
            get {
                return this.sidField;
            }
            set {
                if ((this.sidField.Equals(value) != true)) {
                    this.sidField = value;
                    this.RaisePropertyChanged("sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListAgentsResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class ListAgentsResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.AgentInfoDataContract[] agentInfosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.AgentInfoDataContract[] agentInfos {
            get {
                return this.agentInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.agentInfosField, value) != true)) {
                    this.agentInfosField = value;
                    this.RaisePropertyChanged("agentInfos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMyInfoRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class GetMyInfoRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sid {
            get {
                return this.sidField;
            }
            set {
                if ((this.sidField.Equals(value) != true)) {
                    this.sidField = value;
                    this.RaisePropertyChanged("sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMyInfoResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/khemo.tabitelephony.webservice.api.DataCo" +
        "ntracts")]
    [System.SerializableAttribute()]
    public partial class GetMyInfoResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.AgentInfoDataContract agentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] callsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.AgentInfoDataContract agentInfo {
            get {
                return this.agentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.agentInfoField, value) != true)) {
                    this.agentInfoField = value;
                    this.RaisePropertyChanged("agentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HermesWebServiceClient.ServiceReference1.CallInfoDataContract[] calls {
            get {
                return this.callsField;
            }
            set {
                if ((object.ReferenceEquals(this.callsField, value) != true)) {
                    this.callsField = value;
                    this.RaisePropertyChanged("calls");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHermes_Api")]
    public interface IHermes_Api {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHermes_Api/login", ReplyAction="http://tempuri.org/IHermes_Api/loginResponse")]
        HermesWebServiceClient.ServiceReference1.LoginResponseMessage login(HermesWebServiceClient.ServiceReference1.LoginRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHermes_Api/logout", ReplyAction="http://tempuri.org/IHermes_Api/logoutResponse")]
        HermesWebServiceClient.ServiceReference1.LogoutResponseMessage logout(HermesWebServiceClient.ServiceReference1.LogoutRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHermes_Api/getAgentInfo", ReplyAction="http://tempuri.org/IHermes_Api/getAgentInfoResponse")]
        HermesWebServiceClient.ServiceReference1.GetAgentInfoResponseMessage getAgentInfo(HermesWebServiceClient.ServiceReference1.GetAgentInfoRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHermes_Api/listAgents", ReplyAction="http://tempuri.org/IHermes_Api/listAgentsResponse")]
        HermesWebServiceClient.ServiceReference1.ListAgentsResponseMessage listAgents(HermesWebServiceClient.ServiceReference1.ListAgentsRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHermes_Api/getMyInfo", ReplyAction="http://tempuri.org/IHermes_Api/getMyInfoResponse")]
        HermesWebServiceClient.ServiceReference1.GetMyInfoResponseMessage getMyInfo(HermesWebServiceClient.ServiceReference1.GetMyInfoRequestMessage request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IHermes_ApiChannel : HermesWebServiceClient.ServiceReference1.IHermes_Api, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Hermes_ApiClient : System.ServiceModel.ClientBase<HermesWebServiceClient.ServiceReference1.IHermes_Api>, HermesWebServiceClient.ServiceReference1.IHermes_Api {
        
        public Hermes_ApiClient() {
        }
        
        public Hermes_ApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Hermes_ApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hermes_ApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hermes_ApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HermesWebServiceClient.ServiceReference1.LoginResponseMessage login(HermesWebServiceClient.ServiceReference1.LoginRequestMessage request) {
            return base.Channel.login(request);
        }
        
        public HermesWebServiceClient.ServiceReference1.LogoutResponseMessage logout(HermesWebServiceClient.ServiceReference1.LogoutRequestMessage request) {
            return base.Channel.logout(request);
        }
        
        public HermesWebServiceClient.ServiceReference1.GetAgentInfoResponseMessage getAgentInfo(HermesWebServiceClient.ServiceReference1.GetAgentInfoRequestMessage request) {
            return base.Channel.getAgentInfo(request);
        }
        
        public HermesWebServiceClient.ServiceReference1.ListAgentsResponseMessage listAgents(HermesWebServiceClient.ServiceReference1.ListAgentsRequestMessage request) {
            return base.Channel.listAgents(request);
        }
        
        public HermesWebServiceClient.ServiceReference1.GetMyInfoResponseMessage getMyInfo(HermesWebServiceClient.ServiceReference1.GetMyInfoRequestMessage request) {
            return base.Channel.getMyInfo(request);
        }
    }
}
